openapi: 3.1.0

info:
  title: Prediction Guard API
  description: "This is the Prediction Guard API, designed to provide various language-related services and checks."
  version: "1.2"

servers:
  - url: https://{your-pg.api-domain}.com

paths:
  /documents/extract:
    post:
      summary: Documents Extract
      description: This endpoint allows you to parse text from documents using OCR.
      parameters:
        - name: Toxicity
          in: header
          description: Whether to check the output for toxicity.
          schema:
            type: boolean
          example: true
        - name: Pii
          in: header
          description: Whether to check the output for Pii, and what to do if found. Supported values are 'replace' and 'block'.
          schema:
            type: string
          example: "replace"
        - name: Replace-Method
          in: header
          description: Method to replace any found PII. Supported values are 'category', 'fake', 'mask', and 'random'.
          schema:
            type: string
          example: "category"
        - name: Entity-List
          in: header
          description: An array of entity types that the PII check should ignore.
          schema:
            type: array
            items:
              type: string
              description: An entity type that the PII check should ignore.
          example: ["ADDRESS"]
        - name: Injection
          in: header
          description: Whether to check the output for a prompt injection.
          schema:
            type: boolean
          example: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The document file to upload.
                embedImages:
                  type: boolean
                  description: Whether to embed images from the document.
                outputFormat:
                  type: string
                  description: The output format for the content of the document.
                chunkDocument:
                  type: boolean
                  description: Whether to separate the document into chunks.
                chunkSize:
                  type: integer
                  description: The size of chunks for the documents.
                enableOCR:
                  type: boolean
                  description: Whether to enable OCR for document parsing.
              required:
                - file
            examples:
              multipart/form-data:
                value:
                  file: "sample.pdf"
                  embedImages: false
                  outputFormat: "markdown"
                  chunkDocument: true
                  chunkSize: 1000
                  enableOCR: true
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: The parsed document title.
                  contents:
                    type: string
                    description: The parsed document contents.
                  count:
                    type: integer
                    description: The word count for the document.
              examples:
                multipart/form-data:
                  value:
                    title: "sample.pdf"
                    contents: "## Sample PDF\n\n## This is a simple PDF file. Fun fun fun.\n\nLorem ipsum dolor sit amet,  consectetuer adipiscing elit. Phasellus facilisis odio sed mi. Curabitur suscipit..."
                    count: 3041
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
  schemas:
